### ISSUE TITLE
SoftwareSerial issues

### ISSUE THREAD

**Issue by dmnc-net** [yurisliepins/ModuleSerial#1]
Hi, please is it possible to use AltsoftSerial or NeoSWSerial instead of SoftwareSerial which is generally very [unrecommended](https://arduino.stackexchange.com/a/34130/6220) solution or is there any issue with those alternative sw serials? Thanks

**Comment by jurisliepins** [comment]
I've not tried it but I don't see why not. You'd have to replace all calls to SoftwareSerial in all source files. I would imagine that using AltsoftSerial or NeoSWSerial would decrease the available memory though. I can redefine ModuleSerialCore as an abstract class, so that you can re-implement read/write calls yourself, with any lib that you want.

**Comment by jurisliepins** [comment]
I've added an AltSoftSerial branch to the repo. You'd have to copy the AltSoftSerial lib source code to the root dir yourself though. Although I can't get the AltSoftSerial to print to the serial connection. If you can find what's up, make a pull request, I'll add your fix to the repo.
